### ISSUE TITLE
Pandas SettingWithCopyWarning

### ISSUE THREAD

**Issue by ngould** [dodger487/dplython#17] opened 2016-04-05 02:28 UTC
I'm seeing this warning from Pandas:

```
.............../Users/nathangould/workspace/dplython/dplython/dplython.py:393: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df[key] = val.applyFcns(df)
........................................
```

Since this happening inside mutate(), I think df[key] would be a new column, and therefore not be a copy. So I don't yet understand what pandas is complaining about, but it could be worth looking into.

**Comment by has2k1** [comment] 2016-04-05 02:51
It is saying that `df` is a copy of a slice, there is likely a `master_df` that isn't getting updated. So any new column on `df` will not show up on `master_df`. In some cases pandas gives false warnings.

**Comment by ngould** [comment] 2016-04-05 03:33
I also think a false warning is likely. It would be nice to either confirm the correctness of the existing code, or rewrite it in a way that avoids the warning.

**Comment by dodger487** [comment] 2016-04-05 04:07
Hi all,
I'm pretty sure this is caused by code happening in the current way
grouping works. I'm working on that now and it should be fixed soon.

**Comment by dodger487** [comment] 2016-04-05 14:41
Alright, #18 has fixed this issue-- no more of this warning when running tests. It seems like there's a warning for using "assertEquals" in the tests, but the warning messages are almost cleaned up.

**Closed as completed by dodger487** 2016-04-05 14:41 UTC
