### ISSUE TITLE
NameError: 'DplyFrame' is not defined

### ISSUE THREAD

**Issue by barcadad** [dodger487/dplython#1] opened 2016-03-22 03:52 UTC
I'm a recent Python convert from R, so this is great to see.  I have what could be a simple file I/O error when I run your example, but not sure:
`
/anaconda/bin/python /Users/myusername/code/dplyr_example1.py
Traceback (most recent call last):
  File "/Users/myusername/code/dplyr_example1.py", line 1, in <module>
    from dplython import *
  File "/anaconda/lib/python3.4/site-packages/dplython/__init__.py", line 4, in <module>
    diamonds = DplyFrame(diamonds)
NameError: name 'DplyFrame' is not defined
`
Any ideas what's wrong?

**Comment by dodger487** [comment] 2016-03-22 04:35
This could be a few things: 1) an issue with anaconda, 2) caused by using
python 3 (this is unfortunately only python 2 compatible right now) or 3)
something else.

If you can try this outside of anaconda and with python 2.7, that'd be a
help! If it's still broken I'll have some more debugging to do.

**Comment by Nagasaki45** [comment] 2016-03-25 09:51
The issue caused by using python 3 (due to implicit relative import in the code, which is not allowed in python 3). It was fixed in e751ae1f41762e93bcb1e237f0f9633048eb448b, and overall python 3 compatibility was added in b2229250a08668f63762079cc503f0b6a284e8a5. Please reinstall and try again.

**Comment by dodger487** [comment] 2016-03-28 18:54
It sounds like this issue most likely fixed with the Python 3 compatibility upgrade. @barcadad, can you take a look in the next few days and close this if so?

**Closed as completed** 2016-04-09 21:29 UTC
